spring:
  application:
    name: jdbc

logging:
  level:
    # org.springframework.security: DEBUG

---

spring:
  profiles: client

      
server:
  port: 8081
  
  
security:
  user:
    name: siva
    password: secret
    role: ADMIN,USER 